server:
  port: 8082

spring:
  application:
    name: arena

  datasource:
    url: jdbc:mysql://10.0.75.1:3306/arenadb
    username: aneo
    password: devoxx2017
    platform: mysql
    testWhileIdle: true
    validationQuery: SELECT 1;
    initialize: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: ERROR
    fr.aneo: INFO

arena:
  startAt: 9
  endAt: 17
  inSimuMode: true # if true, schedules fights every simuModeInterval seconds, if false, apply the model between startAt and endAt
  simuModeInterval: 10 # define the interval to schedules fights at

leaderboardUrl: "http://leaderboard-web:8081/leaderboard"
heroApiUrl: "http://hero-web:8080"

---

spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/arenadb

leaderboardUrl: http://localhost:8081/leaderboard
heroApiUrl: http://localhost:8080