server:
  port: 8083

hero:
  datasource:
    url: "jdbc:mysql://10.0.75.1:3306/herodb"
    username: aneo
    password: devoxx2017

arena:
  datasource:
    url: "jdbc:mysql://10.0.75.1:3306/arenadb"
    username: aneo
    password: devoxx2017

spring:
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---

spring:
  profiles: local

hero:
  datasource:
    url: "jdbc:mysql://localhost:3306/herodb"

arena:
  datasource:
    url: "jdbc:mysql://localhost:3306/arenadb"
