
aneo.security.jwt:
  expirationTime: 86400000 # 1 day = 1000 * 60 * 60 * 24 ms
  issuer: aneo

spring.datasource:
  url: jdbc:mysql://10.0.75.1:3306/herodb
  username: aneo
  password: devoxx2017
  platform: mysql
  testWhileIdle: true
  validationQuery: SELECT 1;
  initialize: false

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

liquibase:
  change-log: classpath:/changelog/db.changelog-master.yaml

quizz:
  startAt: 9
  endAt: 17
  interval: 30
  intervalTimeUnit: MINUTES
  intervalInMinutes: 1
  inSimuMode: true # if true, the quizz runs in simulation mode, starting now, every simuModeInterval seconds
  simuInterval: 10 # in seconds
  simuIntervalTimeUnit: SECONDS

---

spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/arenadb